// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { loadEnvFile } from "node:process";
import { defineConfig } from "prisma/config";

try {
  loadEnvFile(".env");
} catch {
  // Vercel and other hosts provide env vars directly.
}

const databaseUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  ...(databaseUrl
    ? {
      datasource: {
        url: databaseUrl,
      },
    }
    : {}),
});
